/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.databarang;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZFR
 */
public class BarangFrame extends javax.swing.JFrame {

    ArrayList<Barang> barangList = new ArrayList<>();  // Untuk menyimpan daftar objek Barang
    Connection conn;  // Untuk Mengkoneksikan ke database
    PreparedStatement ps;  // Eksekusi pernyataan SQL terparameter
    ResultSet rs;  // Menyimpan hasil dari query database

    
    
    public BarangFrame() {
        
    initComponents(); 
    
    try {
        conn = DriverManager.getConnection("jdbc:mysql://localhost/barang", "root", ""); // Mendapatkan koneksi ke database MySQL
    } catch (SQLException ex) {
        Logger.getLogger(BarangFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    tampilkanBarang(); // Memanggil metode tampilkanBarang() 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtJudul = new javax.swing.JLabel();
        txtKode = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        txtDeskripsi = new javax.swing.JLabel();
        fieldKode = new javax.swing.JTextField();
        fieldNama = new javax.swing.JTextField();
        fieldDeskripsi = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtJudul.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        txtJudul.setText("DATA BARANG");

        txtKode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKode.setText("Kode Barang");

        txtNama.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNama.setText("Nama Barang");

        txtDeskripsi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDeskripsi.setText("Deskripsi");

        fieldKode.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fieldKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldKodeActionPerformed(evt);
            }
        });

        fieldNama.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaActionPerformed(evt);
            }
        });

        fieldDeskripsi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnSimpan.setBackground(new java.awt.Color(153, 255, 51));
        btnSimpan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        tblBarang.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        btnUbah.setBackground(new java.awt.Color(255, 255, 51));
        btnUbah.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 153, 102));
        btnHapus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtJudul)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtKode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldKode))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama)
                            .addComponent(txtDeskripsi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUbah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapus))))
                    .addComponent(jScrollPane1))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtJudul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKode)
                    .addComponent(fieldKode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeskripsi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaActionPerformed

    private void fieldKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldKodeActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        
        String sql = "INSERT INTO data_barang VALUES(?, ?, ?)"; // Query untuk melakukan Tambah data ke tabel data_barang
        
        try {
            ps = conn.prepareStatement(sql);// Mempersiapkan statement SQL untuk eksekusi INSERT
            
            
            // Mengatur nilai parameter sesuai dengan nilai yang diambil dari field teks pada GUI
            ps.setString(1, fieldKode.getText());
            ps.setString(2, fieldNama.getText());
            ps.setString(3, fieldDeskripsi.getText());
            
            // Mengeksekusi pernyataan SQL untuk menyimpan data
            int simpan = ps.executeUpdate();
            
            // Menampilkan pesan berhasil atau gagal berdasarkan hasil eksekusi
            if(simpan > 0){
                JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
                
                
//              Mengatur agar setelah menambahkan data fieldnya langsung kosong
                fieldKode.setText(null); 
                fieldNama.setText(null);
                fieldDeskripsi.setText(null);
                
            }else{
                JOptionPane.showMessageDialog(this, "Data Gagal Disimpan");
            }
            
            tampilkanBarang();
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(BarangFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
                // TODO add your handling code here:
        int index = tblBarang.getSelectedRow();  // Mendapatkan indeks baris yang dipilih dari tabel
        
         if (index == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin Diubah.");
            return;
        }
         
         
        Barang br = barangList.get(index);  // Mendapatkan objek Barang dari ArrayList berdasarkan indeks
        
        br.setNama_barang(fieldNama.getText());  // Mengatur nilai nama_barang dari objek Barang
        br.setDeskripsi(fieldDeskripsi.getText());  // Mengatur nilai deskripsi dari objek Barang
        
        String sql = "UPDATE data_barang SET nama_barang = ?, deskripsi = ? WHERE kode_barang = ?";
        
        try {
            ps = conn.prepareStatement(sql);
            
            // Mengatur nilai parameter dalam pernyataan SQL UPDATE
            ps.setString(1, br.getNama_barang());
            ps.setString(2, br.getDeskripsi());
            ps.setString(3, br.getKode_barang());
            
            int update  = ps.executeUpdate();  // Eksekusi pernyataan SQL UPDATE
            
            if(update > 0){
                JOptionPane.showMessageDialog(this, "Data Berhasil Di Ubah");
                
                // Mengatur agar setelah mengupdate data, fieldnya langsung kosong
                fieldKode.setText(null); 
                fieldNama.setText(null);
                fieldDeskripsi.setText(null);
                
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Di Ubah");
            }
            
            tampilkanBarang();  // Memanggil method untuk menampilkan ulang data barang ke dalam tabel
            
        } catch (SQLException ex) {
            Logger.getLogger(BarangFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        int index = tblBarang.getSelectedRow();  // Mendapatkan indeks baris yang dipilih dari tabel

        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus.");
            return;
        }

        Barang br = barangList.get(index);  // Mendapatkan objek Barang dari ArrayList berdasarkan indeks

            // Menampilkan dialog konfirmasi sebelum menghapus data
            int option = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data?", "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);
            if (option != JOptionPane.YES_OPTION) {
                return;  // Menghentikan proses jika pengguna memilih "NO"
            }

            String sql = "DELETE FROM data_barang WHERE kode_barang = ?";

            try {
                ps = conn.prepareStatement(sql);
                ps.setString(1, br.getKode_barang());

                int hapus = ps.executeUpdate();

                if (hapus > 0) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");

                    // Mengatur agar setelah menghapus data, fieldnya langsung kosong
                    fieldKode.setText(null);
                    fieldNama.setText(null);
                    fieldDeskripsi.setText(null);

                    // Menghapus objek Barang dari ArrayList setelah dihapus dari database
                    barangList.remove(index);

                    // Memperbarui tampilan tabel
                    tampilkanBarang();

                } else {
                    JOptionPane.showMessageDialog(this, "Data Gagal Dihapus");
                }

            } catch (SQLException ex) {
                Logger.getLogger(BarangFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:
        int index = tblBarang.getSelectedRow();  // Mendapatkan indeks baris yang dipilih dari tabel
        Barang br = barangList.get(index);  // Mendapatkan objek Barang dari ArrayList berdasarkan indeks
        
        // Mengatur nilai field teks dengan nilai dari objek Barang yang dipilih
        fieldKode.setText(br.getKode_barang());
        fieldNama.setText(br.getNama_barang());
        fieldDeskripsi.setText(br.getDeskripsi());
    }//GEN-LAST:event_tblBarangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField fieldDeskripsi;
    private javax.swing.JTextField fieldKode;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBarang;
    private javax.swing.JLabel txtDeskripsi;
    private javax.swing.JLabel txtJudul;
    private javax.swing.JLabel txtKode;
    private javax.swing.JLabel txtNama;
    // End of variables declaration//GEN-END:variables

    private void tampilkanBarang() {
        
        barangList.clear(); // Menghapus isi dari ArrayList barangList 
        
        String sql = "SELECT * FROM data_barang";
        
        try {
            ps = conn.prepareStatement(sql); // Mempersiapkan statement SQL
            rs = ps.executeQuery(); // Mengeksekusi query dan mendapatkan hasilnya
            
            
            // Memproses hasil query dan menambahkan data barang ke dalam ArrayList barangList
            while(rs.next()){
                barangList.add(
                        new Barang(
                                rs.getString("kode_barang"),
                                rs.getString("nama_barang"),
                                rs.getString("deskripsi")
                        )
                );
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(BarangFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String[] kolom = {"Kode Barang", "Nama Barang", "Deskripsi"}; // Menyiapkan kolom-kolom untuk tabel
        Object[][] data = new Object[barangList.size()][3]; // Menyiapkan array untuk data yang akan ditampilkan di tabel
        
        for(int i = 0; i < barangList.size(); i++){
            data[i][0] = barangList.get(i).getKode_barang();
            data[i][1] = barangList.get(i).getNama_barang();
            data[i][2] = barangList.get(i).getDeskripsi();
        }
        
        DefaultTableModel tableModel = new DefaultTableModel(data, kolom); // Membuat DefaultTableModel dengan data dan kolom yang sudah disiapkan
        tblBarang.setModel(tableModel);// Mengatur model tabel (tblBarang) dengan DefaultTableModel yang sudah dibuat
        
        
    }
    
}
